module.exports = {
    symbols: [
        // Forex symbols
        { custom: "XAUUSD", yahoo: "GC=F" }, // Gold Futures
        { custom: "EURUSD", yahoo: "EURUSD=X" },
        { custom: "USDJPY", yahoo: "JPY=X" },
        { custom: "GBPUSD", yahoo: "GBPUSD=X" },
        { custom: "USDCHF", yahoo: "CHF=X" },
        { custom: "AUDUSD", yahoo: "AUDUSD=X" },
        { custom: "USDCAD", yahoo: "CAD=X" },
        { custom: "EURGBP", yahoo: "EURGBP=X" },
        { custom: "EURAUD", yahoo: "EURAUD=X" },
        { custom: "GBPJPY", yahoo: "GBPJPY=X" },
        { custom: "NZDUSD", yahoo: "NZDUSD=X" },
        { custom: "EURJPY", yahoo: "EURJPY=X" },
        { custom: "EURCHF", yahoo: "EURCHF=X" },
        { custom: "EURCAD", yahoo: "EURCAD=X" },
        { custom: "CADJPY", yahoo: "CADJPY=X" },
        { custom: "GBPAUD", yahoo: "GBPAUD=X" },
        { custom: "GBPCAD", yahoo: "GBPCAD=X" },
        { custom: "GBPCHF", yahoo: "GBPCHF=X" },
        { custom: "AUDCHF", yahoo: "AUDCHF=X" },
        { custom: "EURNZD", yahoo: "EURNZD=X" },
        { custom: "GBPNZD", yahoo: "GBPNZD=X" },
        { custom: "AUDCAD", yahoo: "AUDCAD=X" },
        { custom: "AUDJPY", yahoo: "AUDJPY=X" },

        // Crypto symbols
        { custom: "BTCUSD", yahoo: "BTC-USD" },
        { custom: "ETHUSD", yahoo: "ETH-USD" },
        { custom: "XRPUSD", yahoo: "XRP-USD" },
        { custom: "BNBUSD", yahoo: "BNB-USD" },
        { custom: "SOLUSD", yahoo: "SOL-USD" },
        { custom: "DOGEUSD", yahoo: "DOGE-USD" },
        { custom: "CHZUSD", yahoo: "CHZ-USD" },
        { custom: "TRXUSD", yahoo: "TRX-USD" },
        { custom: "SHIBUSD", yahoo: "SHIB-USD" },
        { custom: "AVAXUSD", yahoo: "AVAX-USD" },
        { custom: "ADAUSD", yahoo: "ADA-USD" },
        { custom: "CAKEUSD", yahoo: "CAKE-USD" },
        { custom: "LINKUSD", yahoo: "LINK-USD" },
        { custom: "TONUSD", yahoo: "TON-USD" },
        { custom: "SUIUSD", yahoo: "SUI-USD" },
        { custom: "NEARUSD", yahoo: "NEAR-USD" },
        { custom: "ICPUSD", yahoo: "ICP-USD" },
        { custom: "DAIUSD", yahoo: "DAI-USD" },
        { custom: "ALGOUSD", yahoo: "ALGO-USD" },
        { custom: "FTMUSD", yahoo: "FTM-USD" },
        { custom: "ATOMUSD", yahoo: "ATOM-USD" },
        { custom: "MANAUSD", yahoo: "MANA-USD" },
        { custom: "MATICUSD", yahoo: "MATIC-USD" },
        { custom: "MINAUSD", yahoo: "MINA-USD" },
        { custom: "DOTUSD", yahoo: "DOT-USD" },
        { custom: "UNIUSD", yahoo: "UNI-USD" },
        { custom: "FLOWUSD", yahoo: "FLOW-USD" },
        { custom: "SANDUSD", yahoo: "SAND-USD" },
    ],
    emaPeriod: 155,
    ichimokuPeriod: 55,
    timeFrames: ["1d", "1h"], // Supported intervals
    checkInterval: "*/10 * * * *", // Every 10 minutes
    allowedUserId: isNaN(parseInt(process.env.ALLOWED_CHAT_ID)) ? null : parseInt(process.env.ALLOWED_CHAT_ID),
};
